### ISSUE TITLE
Cant open shop menu, game thinks im already in one

### ISSUE THREAD

**Issue by witheredchica** [efeketket/PlayerShops#2]
it thinks i have a shop open, but i do not. this prevents me from opening any of my shops until i remove and re-add the datapack

![image](https://github.com/efeketket/ketkets-player-shops/assets/151658059/94050c7e-0f99-4717-839a-77c4b92dc015)

**Comment by ari-party** [comment]
Happened to me. Others forgot to use the close menu, can't open it now.

**Comment by ari-party** [comment]
Happened to me too now.
